services:
  common:
    image: localhost/solar-protocol/base:beta
    build: common
    profiles: ["build"]

  datalogger:
    image: localhost/solar-protocol/datalogger
    build: datalogger
    restart: unless-stopped
    volumes:
      - data:/data
    environment:
      - FAKE_DATA
      - LOGLEVEL
      - PLATFORM

  api:
    image: localhost/solar-protocol/api
    build: api
    restart: unless-stopped
    volumes:
      - data:/data
      - local:/local
    ports:
      - 11215:80

  protocol:
    image: localhost/solar-protocol/protocol
    build: protocol
    restart: unless-stopped
    command: python run.py
    environment:
      - LOGLEVEL
    volumes:
      - data:/data
      - frontend:/frontend
      - local:/local

  web:
    image: docker.io/library/nginx
    restart: unless-stopped
    volumes:
      - data:/data
      - local:/local
      - frontend:/frontend
      - ./dev/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 11221:80

volumes:
  data:
    driver_opts:
      o: bind
      type: none
      device: '${PWD}/data'
  frontend:
    driver_opts:
      o: bind
      type: none
      device: '${PWD}/frontend'
  local:
    driver_opts:
      o: bind
      type: none
      device: '${PWD}/local'
